/*
 * ════════════════════════════════════════════════════════════════════════════
 * FILE: middleware.ts
 * ════════════════════════════════════════════════════════════════════════════
 * WHAT IT DOES:
 *   Runs on every request to /admin/* routes (except /admin/login).
 *   Checks for a valid session cookie — if missing or wrong, redirects to
 *   the login page. This is what keeps the admin panel private.
 *
 * ✏️  THINGS YOU CAN CHANGE:
 *   - Admin password  → set ADMIN_PASSWORD in .env.local
 *                       (default is "admin123" — change this before deploying)
 *   - Cookie name     → COOKIE_NAME constant (no real reason to change this)
 *
 * ⚠️  DO NOT edit this file unless you understand the auth flow.
 *     Breaking it will lock you out of the admin panel.
 * ════════════════════════════════════════════════════════════════════════════
 */

import { NextRequest, NextResponse } from "next/server";

const COOKIE_NAME = "jfcr_admin_session";

async function sha256(message: string): Promise<string> {
  const msgBuffer = new TextEncoder().encode(message);
  const hashBuffer = await crypto.subtle.digest("SHA-256", msgBuffer);
  const hashArray = Array.from(new Uint8Array(hashBuffer));
  return hashArray.map((b) => b.toString(16).padStart(2, "0")).join("");
}

export async function middleware(request: NextRequest) {
  const { pathname } = request.nextUrl;

  // Only protect /admin routes (not /admin/login itself)
  if (pathname.startsWith("/admin") && pathname !== "/admin/login") {
    const session = request.cookies.get(COOKIE_NAME)?.value;
    if (!session) {
      return NextResponse.redirect(new URL("/admin/login", request.url));
    }

    const adminPassword = process.env.ADMIN_PASSWORD || "admin123";
    const expected = await sha256(adminPassword);
    if (session !== expected) {
      return NextResponse.redirect(new URL("/admin/login", request.url));
    }
  }

  return NextResponse.next();
}

export const config = {
  matcher: ["/admin/:path*"],
};
